<?php
$enable = Mage::getStoreConfig('manageteamsection/manageteamgroup/enable');
if ($enable) {
    $currId = $this->getRequest()->getParam('id');
    if ($currId != ''):
        $collection = Mage::getModel('manageteam/manageteam')->load($currId);
        $media_url = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);
        ?>
        <div class="ourteam-view">
            <div class="ourteam-detail">
                <div class="team-block-left">
                    <?php if ($collection->getImage()) { ?>
                        <img src="<?php echo $media_url . $collection->getImage(); ?>" alt="<?php echo $this->htmlEscape($collection->getName()); ?>" />
                    <?php } else { ?>
                        <img src="<?php echo $this->getSkinUrl('images/manageteam/manageteam.png'); ?>" alt="<?php echo $this->htmlEscape($collection->getName()); ?>" />
                    <?php } ?>
                </div>
                <div class="team-block-right">
                    <h2 class="ourteam-name">
                        <b><?php echo Mage::helper('manageteam')->__('Name'); ?>: </b><?php echo $collection->getName(); ?>
                    </h2>
                    <div class="ourteam-short_desc">
                        <b><?php echo Mage::helper('manageteam')->__('Designation'); ?>: </b><?php echo $collection->getDesignation(); ?>
                    </div>
                    <div class="ourteam-description">
                        <b><?php echo Mage::helper('manageteam')->__('Description'); ?>: </b><?php echo $collection->getDescription(); ?>
                    </div>
                    <div class="ourteam-short_desc">
                        <b><?php echo Mage::helper('manageteam')->__('Facebook Url'); ?>: </b><a target="_new" href="<?php echo $collection->getFacebookurl(); ?>"><?php echo $collection->getFacebookurl(); ?></a>
                    </div>
                    <div class="ourteam-short_desc">
                        <b><?php echo Mage::helper('manageteam')->__('Google+ Url'); ?>: </b><a target="_new" href="<?php echo $collection->getGoogleurl(); ?>"><?php echo $collection->getGoogleurl(); ?></a>
                    </div>
                    <div class="ourteam-short_desc">
                        <b><?php echo Mage::helper('manageteam')->__('Twitter Url'); ?>: </b><a target="_new" href="<?php echo $collection->getTwitterurl(); ?>"><?php echo $collection->getTwitterurl(); ?></a>
                    </div>
                    <div class="ourteam-short_desc">
                        <b><?php echo Mage::helper('manageteam')->__('Email'); ?>: </b><a href="mailto:<?php echo $collection->getEmail(); ?>"><?php echo $collection->getEmail(); ?></a>
                    </div>
                </div>
            </div>
        </div>
        <div class="back-btn">
            <a class="read-more" href="<?php echo $this->getBaseUrl() . 'manageteam/index/index/'; ?>" title="Back">
                <?php echo __('Back'); ?>	
            </a>
        </div>

    <?php else: ?>
        <div class="page-title ourteam-title">
            <h1><?php echo Mage::helper('manageteam')->__('Our Team') ?></h1>
        </div>
        <?php
        //get collection of manageteam
        $collection = $this->getCollection();
        $size = $collection->getSize();
        $media_url = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA);
        ?>
        <?php if ($size > 0): ?>
            <div class="ourteam-list-container">
                <?php echo $this->getPagerHtml(); ?>
                <ul class="team-wrapper">
                    <?php foreach ($collection as $teamData): ?>
                        <li class="ourteam-list-item">
                            <a href="<?php echo $this->getBaseUrl() . 'manageteam/index/index/id/' . $teamData->getManageteam_id(); ?>" title="<?php echo $this->htmlEscape($teamData->getName()) ?>">
                                <?php if ($teamData->getImage()): ?>
                                    <img class="member_avatar " src="<?php echo $media_url . $teamData->getImage(); ?>" alt="<?php echo $teamData->getName(); ?>" width="190" height="190"/>
                                <?php else: ?>
                                    <img class="member_avatar" src="<?php echo $this->getSkinUrl('images/manageteam/manageteam.png') ?>" alt="<?php echo $teamData->getName(); ?>" width="190" height="190"/>
                                <?php endif; ?>
                            </a>
                            <h2 class="full-name">
                                <?php echo $teamData->getName(); ?>
                            </h2>
                            <?php if ($teamData->getDesignation()): ?>
                                <div id="greg_description"><?php echo $teamData->getDesignation(); ?> </div>
                            <?php endif; ?>
                            <?php if ($teamData->getDescription()): ?>
                                <a class="read-more" href="<?php echo $this->getBaseUrl() . 'manageteam/index/index/id/' . $teamData->getManageteam_id(); ?>" title="<?php echo $this->htmlEscape($teamData->getName()) ?>">
                                    <?php echo __('View Details'); ?>	
                                </a>
                            <?php endif; ?>
                        </li>
                    <?php endforeach; ?>
                    <?php
                    ?>
                </ul>
                <?php echo $this->getPagerHtml(); ?>
            </div>
        <?php else : ?>
            <?php echo Mage::helper('manageteam')->__('There are no team member found at this moment'); ?>
        <?php endif; ?>
    <?php endif; ?>
<?php } ?>